### ISSUE TITLE
Create an Account model with "username" field.

### ISSUE THREAD

**Issue by excid3** [excid3/sponsor-hub#2]
This will be used for each Sponsor account that you might have on GitHub: https://github.com/sponsors/accounts

**Comment by rlogwood** [comment]
The github APIs use `login` and `id` for users instead of `username` so the `GithubAccount` for sponsor-hub was setup with `login` and `ghid`. The github id (`ghid`) was included because github allows you to change your login name AFAIK and we'd need the `ghid` to re-associate/assciate sponsor-hub data with a changed login name.

The models are still on a branch and we can destroy and change if needed, see template:
https://github.com/excid3/sponsor-hub/blob/user-models-initial-version/lib/setup/generate_user_models_template.rb
